# Generated by Django 4.1.7 on 2023-03-23 10:05

from django.db import migrations, models
import django.db.models.deletion
import llab2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llab2', '0002_delete_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train'), ('Plane', 'Plane')], default='no type', max_length=10)),
                ('number', models.CharField(max_length=10, unique=True, validators=[llab2.models.validate_number])),
                ('num_of_passengers', models.CharField(blank=True, max_length=10, validators=[llab2.models.validate_number])),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route', to='llab2.route')),
            ],
        ),
    ]
